### ISSUE TITLE
Suggested tool for csv parsing

### ISSUE THREAD

**Issue by smouzakitis** [LinDA-tools/transformation#1]
A suggested tool for csv parsing could be:
https://github.com/jdunck/python-unicodecsv
This package also has a sniffer method for autodetecting delimiters, etc....
https://docs.python.org/2/library/csv.html

or an alternative for javascript side of things

http://papaparse.com/

there is no need for a custom solution

**Comment by bbrand84** [comment]
included https://docs.python.org/2/library/csv.html
