### ISSUE TITLE
Add xlrd to project requirements

### ISSUE THREAD

**Issue by dipapaspyros** [LinDA-tools/transformation#19]

**Comment by almey** [comment]
at the moment we use pandas to read excel files. do you want we switch to xlrd instead of pandas?

**Comment by dipapaspyros** [comment]
No, probably you just import the lib somewhere because when i first run the app it showed an error that the xlrd package is missing, which was fixed when i manually run `pip install xlrd`

**Comment by almey** [comment]
ok, i added xlrd to the requirements
