### ISSUE TITLE
Remove the % symbol next to ranking

### ISSUE THREAD

**Issue by dipapaspyros** [LinDA-tools/transformation#21]
The ranking of each term is not a percentage

**Comment by bbrand84** [comment]
done

**Comment by bbrand84** [comment]
@dipapaspyros In my opinion, the ranking is not very transparent. I don't know how much effort it would be, but a ranking form 1 -100 would be more comprehensible. also sometimes words that should match the search term 100% are ranked lower than other. In case you have some spare time ;)

**Comment by dipapaspyros** [comment]
Will improve the api & range rankings from 1 - 100 in the next 3-4 days, some options are prioritized because of the prominence of the vocabularies that define them
