### ISSUE TITLE
Funtioning back button

### ISSUE THREAD

**Issue by lfarid** [LinDA-tools/transformation#8]
The user should be able to move between steps while retaining the state of the transformation mappings. This is related to #6 .

**Comment by bbrand84** [comment]
working, but reconciliation results in predicate and subject step are still refetched from the oracle service , not loaded from model again ( issue #24 )

**Comment by lfarid** [comment]
- Also in step 3 - the base URL is not saved.
- We should allow the user to go back to step 1 - upload, while retaining the state of the selected columns and the uploaded file. this is important, imho.

**Comment by bbrand84** [comment]
base url is saved - I cannot replicate what you mean.

why would you want to upload a completely new file and save the state of your old one?
